name: publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.7

    - name: Install dependencies
      run: go mod download
      env:
        GOPATH: /home/runner/work/chglog/go

    - name: Build
      run: make package
      env:
        GOPATH: /home/runner/work/chglog/go

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: chglog-*.tar.xz
